---
abstract: 'Simple Interface to Amazon Web Service using WebService::Simple'
author:
  - 'Yusuke Wada <yusuke at kamawada.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Simple-AWS
no_index:
  directory:
    - inc
    - t
requires:
  Digest::SHA: 0
  Filter::Util::Call: 0
  URI::Escape: 0
  WebService::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yusukebe/WebService-Simple-AWS.git
version: 0.01
